### ISSUE TITLE
Forked example repo pattern makes external contribution hard.

### ISSUE THREAD

**Issue by moxious** [eidolon-ai/base-agent-machine#4]
Several things: 

- The quickstart repo doesn't have issues enabled (so I'm filing this on the wrong repo here)
- Quickstart repo has the wrong link to the quickstart at the very top of the repo. The correct link is https://www.eidolonai.com/docs/quickstart
- I'd submit a PR and fix something so trivial for you, but I can't fork/submit a PR, because I forked a different repo from eidolon and the "internal fork relationships" you have between your repos seems to be confusing Github.  You'll note on my profile I didn't actually fork eidolon-quickstart, 

<img width="425" alt="image" src="https://github.com/user-attachments/assets/aecb87b3-ae36-4717-9219-3ede0d97f0fb">

It looks as though how you've set your templates up as a sort of directed graph of forks makes it challenging for outsiders to deal with them.

<img width="920" alt="image" src="https://github.com/user-attachments/assets/0eb2261b-5b44-464b-af50-c003199baf2d">

If there was an issue or challenge with [web researcher](https://github.com/eidolon-ai/web-researcher) for example, it wouldn't get reported because issues are disabled there as well, and one would need to follow the fork relationships back to agent-machine in order to provide this feedback.

**Comment by LukeLalor** [comment]
hmm, well this is a problem now isn't it. We have been restructuring our issue board and unfortunately this one got lost in the shuffle.

The fork graph was a convenient way to keep our example repos up to date, but it makes it challenging for external contributors to contribute back. It is also nonstandard, and we aren't exactly trying to innovate on project structure. I'll chat with the team about this one and see what we think. Probably better to unlink them, but still grab changes from the template via ci/cd, the remote branch will just need to be specified in the workflow which is fine.

 thanks for reporting this issue @moxious

**Comment by LukeLalor** [comment]
Plan: We can keep our ci/cd pattern the same without actually handling forks. workflows will need to change a bit to accommodate the lack of history. This is a good opportunity to simplify strip down root agent-machine repo to make it less conflict prone. Specifically remove the lock file, remove the agent resource, and simplify tests
